-- MySQL Script generated by MySQL Workbench
-- 11/17/16 11:22:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- Utworzenie bazy danych
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS ksiazka DEFAULT CHARACTER SET 
utf8 COLLATE utf8_unicode_ci;
use ksiazka;

-- -----------------------------------------------------
-- Table `Ksiazka_Polowan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ksiazka_Polowan` (
  `idKsiazka_polowan` INT NULL AUTO_INCREMENT,
  `Rozpoczecie_polowania` DATETIME NULL,
  `Zakonczenie_polowania` DATETIME NULL,
  `Strzaly` INT NULL,
  `Numer_odstrzalu` INT NULL,
  PRIMARY KEY (`idKsiazka_polowan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mysliwy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mysliwy` (
  `idMysliwy` INT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `haslo` VARCHAR(45) NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Numer_pozwolenia` INT NULL,
  `Data_urodzenia` DATE NULL,
  PRIMARY KEY (`idMysliwy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bron` (
  `idBron` INT NULL AUTO_INCREMENT,
  `Numer_broni` INT NULL,
  `Kaliber` DECIMAL(3,1) NULL,
  `Nazwa_broni` VARCHAR(45) NULL,
  `Rodzaj_broni` VARCHAR(45) NULL,
  PRIMARY KEY (`idBron`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zwierzyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zwierzyna` (
  `idZwierzyna` INT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NULL,
  `Okres_ochronny` DATE NULL,
  `Sezon_polowan` DATE NULL,
  `ilosc` INT NULL,
  PRIMARY KEY (`idZwierzyna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rejon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rejon` (
  `idRejon` INT NULL AUTO_INCREMENT,
  `Miejscowosc` VARCHAR(45) NULL,
  `Obwod_lowiecki` VARCHAR(45) NULL,
  `Nazwa_lowiska` VARCHAR(45) NULL,
  `Mysliwy_idMysliwy` INT NOT NULL,
  PRIMARY KEY (`idRejon`, `Mysliwy_idMysliwy`),
  INDEX `fk_Rejon_Mysliwy1_idx` (`Mysliwy_idMysliwy` ASC),
  CONSTRAINT `fk_Rejon_Mysliwy1`
    FOREIGN KEY (`Mysliwy_idMysliwy`)
    REFERENCES `Mysliwy` (`idMysliwy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mysliwy_Ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mysliwy_Ksiazka` (
  `Mysliwy_idMysliwy` INT NOT NULL,
  `Ksiazka_polowan_idKsiazka_polowan` INT NOT NULL,
  PRIMARY KEY (`Mysliwy_idMysliwy`, `Ksiazka_polowan_idKsiazka_polowan`),
  INDEX `fk_Mysliwy_Ksiazka_Ksiazka_Polowan1_idx` (`Ksiazka_polowan_idKsiazka_polowan` ASC),
  CONSTRAINT `fk_Mysliwy_Ksiazka_Mysliwy1`
    FOREIGN KEY (`Mysliwy_idMysliwy`)
    REFERENCES `Mysliwy` (`idMysliwy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mysliwy_Ksiazka_Ksiazka_Polowan1`
    FOREIGN KEY (`Ksiazka_polowan_idKsiazka_polowan`)
    REFERENCES `Ksiazka_Polowan` (`idKsiazka_polowan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mysliwy_Zwierzyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mysliwy_Zwierzyna` (
  `Mysliwy_idMysliwy` INT NOT NULL,
  `Zwierzyna_idZwierzyna` INT NOT NULL,
  PRIMARY KEY (`Mysliwy_idMysliwy`, `Zwierzyna_idZwierzyna`),
  INDEX `fk_Mysliwy_Zwierzyna_Zwierzyna1_idx` (`Zwierzyna_idZwierzyna` ASC),
  CONSTRAINT `fk_Mysliwy_Zwierzyna_Mysliwy1`
    FOREIGN KEY (`Mysliwy_idMysliwy`)
    REFERENCES `Mysliwy` (`idMysliwy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mysliwy_Zwierzyna_Zwierzyna1`
    FOREIGN KEY (`Zwierzyna_idZwierzyna`)
    REFERENCES `Zwierzyna` (`idZwierzyna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mysliwy_Bron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mysliwy_Bron` (
  `Mysliwy_idMysliwy` INT NOT NULL,
  `Bron_idBron` INT NOT NULL,
  PRIMARY KEY (`Mysliwy_idMysliwy`, `Bron_idBron`),
  INDEX `fk_Mysliwy_Bron_Bron1_idx` (`Bron_idBron` ASC),
  CONSTRAINT `fk_Mysliwy_Bron_Mysliwy1`
    FOREIGN KEY (`Mysliwy_idMysliwy`)
    REFERENCES `Mysliwy` (`idMysliwy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mysliwy_Bron_Bron1`
    FOREIGN KEY (`Bron_idBron`)
    REFERENCES `Bron` (`idBron`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ksiazka_Polowan_Rejon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ksiazka_Polowan_Rejon` (
  `Rejon_idRejon` INT NOT NULL,
  `Ksiazka_polowan_idKsiazka_polowan` INT NOT NULL,
  PRIMARY KEY (`Rejon_idRejon`, `Ksiazka_polowan_idKsiazka_polowan`),
  INDEX `fk_Ksiazka_Polowan-Rejon_Ksiazka_Polowan1_idx` (`Ksiazka_polowan_idKsiazka_polowan` ASC),
  CONSTRAINT `fk_Ksiazka_Polowan-Rejon_Rejon1`
    FOREIGN KEY (`Rejon_idRejon`)
    REFERENCES `Rejon` (`idRejon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ksiazka_Polowan-Rejon_Ksiazka_Polowan1`
    FOREIGN KEY (`Ksiazka_polowan_idKsiazka_polowan`)
    REFERENCES `Ksiazka_Polowan` (`idKsiazka_polowan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mysliwy_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mysliwy_roles` (
  `Mysliwy_idMysliwy` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`Mysliwy_idMysliwy`, `roles_id`),
  INDEX `fk_mysliwy_roles_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_mysliwy_roles_Mysliwy1`
    FOREIGN KEY (`Mysliwy_idMysliwy`)
    REFERENCES `Mysliwy` (`idMysliwy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mysliwy_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
